In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape

(5,)

In [20]:
my_lst=[1,2,3,4,5]
my_lst1=[8,2,3,4,5]
my_lst2=[9,2,3,4,5]

arr=np.array([my_lst,my_lst1,my_lst2])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [8, 2, 3, 4, 5],
       [9, 2, 3, 4, 5]])

In [12]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 8],
       [2, 3, 4],
       [5, 9, 2],
       [3, 4, 5]])

In [15]:
# check the shape of the array 

arr.shape

(3, 5)

Indexing

In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [18]:
arr[2]

3

In [21]:
arr

array([[1, 2, 3, 4, 5],
       [8, 2, 3, 4, 5],
       [9, 2, 3, 4, 5]])

In [24]:
arr[0:2,0:2]

array([[1, 2],
       [8, 2]])

In [26]:
arr[1:,3:]

array([[4, 5],
       [4, 5]])

In [27]:
arr=np.arange(0,10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr=np.arange(0,10,step=2)

In [30]:
arr

array([0, 2, 4, 6, 8])

In [33]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])